title: Funakoshi Dojo Paris
# uncomment baseurl if you want to publish the site to a subfolder
#baseurl: /blog
description: Funakoshi Dojo Paris est un club de karaté traditionnel Shotokan situé à Paris 12ème. Cours pour enfants, ados et adultes.
exclude:
- LICENSE
- README.adoc
- Gemfile
- Gemfile.lock
- Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    icons: font
    idseparator: _
    stylesdir: css
    source-highlighter: coderay
masthead_banner: assets/karate_billboard_banner.png